name: flutter_central_dependency

description: A new Flutter package project.
homepage: https://github.com/Sconl
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add your dependencies here
  action_slider: ^0.7.0
  amazon_cognito_identity_dart_2: ^3.6.2
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  bloc: any
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  cloud_firestore_platform_interface: ^6.1.6
  cloud_firestore_web: ^3.10.5
  collection: ^1.18.0
  confetti: ^0.7.0
  custom_appbar:
    git:
      url: git@github.com:Sconl/custom_appbar.git
  custom_splash_screen:
    git:
      url: git@github.com:Sconl/custom_splash_screen.git
  equatable: ^2.0.3
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.12.0
  firebase_storage: ^11.6.10
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.0.0
  flutter_cache_manager: ^3.3.1
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.10+1
  flutter_timeline: ^0.3.0
  font_awesome_flutter: ^10.7.0
  from_css_color: ^2.0.0
  frontend_server_client: ^4.0.0
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  js: ^0.7.1
  json_path: ^0.7.1
  lottie: ^3.1.0
  material_color_utilities: ^0.11.1
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.14.0
  page_transition: ^2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  rive: ^0.13.1
  shape_clipper:
    git:
      url: git@github.com:Sconl/shape_clipper.git
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.1
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.2.2
  sleek_circular_slider: ^2.0.1
  slider_button: ^2.1.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.2
  stream_transform: ^2.1.0
  timeago: ^3.6.1
  timeline_tile: ^2.0.0
  url_launcher: ^6.2.5
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.5
  url_launcher_platform_interface: ^2.3.2
  vector_math: ^2.1.4
  win32: ^5.3.0

dev_dependencies:
  bloc_test: ^9.1.6
  flame_test: ^1.16.0
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.25.2
  test_api: ^0.7.0
  vm_service: ^13.0.0

flutter:
  uses-material-design: true
  #plugin:
    #platforms:
      #android:
        #package: com.example.flutter_central_dependency
        #pluginClass: FlutterCentralDependencyPlugin
      #ios:
        #pluginClass: FlutterCentralDependencyPlugin
  assets:
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/gif_animations/
